// Comprehensive list of country dialing codes (ITU / E.164).
// Used by the WhatsApp / phone number pickers across the app.

export interface CountryCode {
  code: string;      // e.g. "+971"
  country: string;   // e.g. "United Arab Emirates"
  flag: string;      // emoji flag
  iso2: string;      // ISO 3166-1 alpha-2
}

export const COUNTRY_CODES: CountryCode[] = [
  { iso2: "AF", country: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { iso2: "AL", country: "Albania", code: "+355", flag: "🇦🇱" },
  { iso2: "DZ", country: "Algeria", code: "+213", flag: "🇩🇿" },
  { iso2: "AS", country: "American Samoa", code: "+1684", flag: "🇦🇸" },
  { iso2: "AD", country: "Andorra", code: "+376", flag: "🇦🇩" },
  { iso2: "AO", country: "Angola", code: "+244", flag: "🇦🇴" },
  { iso2: "AI", country: "Anguilla", code: "+1264", flag: "🇦🇮" },
  { iso2: "AG", country: "Antigua and Barbuda", code: "+1268", flag: "🇦🇬" },
  { iso2: "AR", country: "Argentina", code: "+54", flag: "🇦🇷" },
  { iso2: "AM", country: "Armenia", code: "+374", flag: "🇦🇲" },
  { iso2: "AW", country: "Aruba", code: "+297", flag: "🇦🇼" },
  { iso2: "AU", country: "Australia", code: "+61", flag: "🇦🇺" },
  { iso2: "AT", country: "Austria", code: "+43", flag: "🇦🇹" },
  { iso2: "AZ", country: "Azerbaijan", code: "+994", flag: "🇦🇿" },
  { iso2: "BS", country: "Bahamas", code: "+1242", flag: "🇧🇸" },
  { iso2: "BH", country: "Bahrain", code: "+973", flag: "🇧🇭" },
  { iso2: "BD", country: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { iso2: "BB", country: "Barbados", code: "+1246", flag: "🇧🇧" },
  { iso2: "BY", country: "Belarus", code: "+375", flag: "🇧🇾" },
  { iso2: "BE", country: "Belgium", code: "+32", flag: "🇧🇪" },
  { iso2: "BZ", country: "Belize", code: "+501", flag: "🇧🇿" },
  { iso2: "BJ", country: "Benin", code: "+229", flag: "🇧🇯" },
  { iso2: "BM", country: "Bermuda", code: "+1441", flag: "🇧🇲" },
  { iso2: "BT", country: "Bhutan", code: "+975", flag: "🇧🇹" },
  { iso2: "BO", country: "Bolivia", code: "+591", flag: "🇧🇴" },
  { iso2: "BA", country: "Bosnia and Herzegovina", code: "+387", flag: "🇧🇦" },
  { iso2: "BW", country: "Botswana", code: "+267", flag: "🇧🇼" },
  { iso2: "BR", country: "Brazil", code: "+55", flag: "🇧🇷" },
  { iso2: "IO", country: "British Indian Ocean Territory", code: "+246", flag: "🇮🇴" },
  { iso2: "VG", country: "British Virgin Islands", code: "+1284", flag: "🇻🇬" },
  { iso2: "BN", country: "Brunei", code: "+673", flag: "🇧🇳" },
  { iso2: "BG", country: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { iso2: "BF", country: "Burkina Faso", code: "+226", flag: "🇧🇫" },
  { iso2: "BI", country: "Burundi", code: "+257", flag: "🇧🇮" },
  { iso2: "KH", country: "Cambodia", code: "+855", flag: "🇰🇭" },
  { iso2: "CM", country: "Cameroon", code: "+237", flag: "🇨🇲" },
  { iso2: "CA", country: "Canada", code: "+1", flag: "🇨🇦" },
  { iso2: "CV", country: "Cape Verde", code: "+238", flag: "🇨🇻" },
  { iso2: "KY", country: "Cayman Islands", code: "+1345", flag: "🇰🇾" },
  { iso2: "CF", country: "Central African Republic", code: "+236", flag: "🇨🇫" },
  { iso2: "TD", country: "Chad", code: "+235", flag: "🇹🇩" },
  { iso2: "CL", country: "Chile", code: "+56", flag: "🇨🇱" },
  { iso2: "CN", country: "China", code: "+86", flag: "🇨🇳" },
  { iso2: "CX", country: "Christmas Island", code: "+61", flag: "🇨🇽" },
  { iso2: "CC", country: "Cocos Islands", code: "+61", flag: "🇨🇨" },
  { iso2: "CO", country: "Colombia", code: "+57", flag: "🇨🇴" },
  { iso2: "KM", country: "Comoros", code: "+269", flag: "🇰🇲" },
  { iso2: "CK", country: "Cook Islands", code: "+682", flag: "🇨🇰" },
  { iso2: "CR", country: "Costa Rica", code: "+506", flag: "🇨🇷" },
  { iso2: "HR", country: "Croatia", code: "+385", flag: "🇭🇷" },
  { iso2: "CU", country: "Cuba", code: "+53", flag: "🇨🇺" },
  { iso2: "CW", country: "Curaçao", code: "+599", flag: "🇨🇼" },
  { iso2: "CY", country: "Cyprus", code: "+357", flag: "🇨🇾" },
  { iso2: "CZ", country: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { iso2: "CD", country: "Democratic Republic of the Congo", code: "+243", flag: "🇨🇩" },
  { iso2: "DK", country: "Denmark", code: "+45", flag: "🇩🇰" },
  { iso2: "DJ", country: "Djibouti", code: "+253", flag: "🇩🇯" },
  { iso2: "DM", country: "Dominica", code: "+1767", flag: "🇩🇲" },
  { iso2: "DO", country: "Dominican Republic", code: "+1809", flag: "🇩🇴" },
  { iso2: "EC", country: "Ecuador", code: "+593", flag: "🇪🇨" },
  { iso2: "EG", country: "Egypt", code: "+20", flag: "🇪🇬" },
  { iso2: "SV", country: "El Salvador", code: "+503", flag: "🇸🇻" },
  { iso2: "GQ", country: "Equatorial Guinea", code: "+240", flag: "🇬🇶" },
  { iso2: "ER", country: "Eritrea", code: "+291", flag: "🇪🇷" },
  { iso2: "EE", country: "Estonia", code: "+372", flag: "🇪🇪" },
  { iso2: "SZ", country: "Eswatini", code: "+268", flag: "🇸🇿" },
  { iso2: "ET", country: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { iso2: "FK", country: "Falkland Islands", code: "+500", flag: "🇫🇰" },
  { iso2: "FO", country: "Faroe Islands", code: "+298", flag: "🇫🇴" },
  { iso2: "FJ", country: "Fiji", code: "+679", flag: "🇫🇯" },
  { iso2: "FI", country: "Finland", code: "+358", flag: "🇫🇮" },
  { iso2: "FR", country: "France", code: "+33", flag: "🇫🇷" },
  { iso2: "GF", country: "French Guiana", code: "+594", flag: "🇬🇫" },
  { iso2: "PF", country: "French Polynesia", code: "+689", flag: "🇵🇫" },
  { iso2: "GA", country: "Gabon", code: "+241", flag: "🇬🇦" },
  { iso2: "GM", country: "Gambia", code: "+220", flag: "🇬🇲" },
  { iso2: "GE", country: "Georgia", code: "+995", flag: "🇬🇪" },
  { iso2: "DE", country: "Germany", code: "+49", flag: "🇩🇪" },
  { iso2: "GH", country: "Ghana", code: "+233", flag: "🇬🇭" },
  { iso2: "GI", country: "Gibraltar", code: "+350", flag: "🇬🇮" },
  { iso2: "GR", country: "Greece", code: "+30", flag: "🇬🇷" },
  { iso2: "GL", country: "Greenland", code: "+299", flag: "🇬🇱" },
  { iso2: "GD", country: "Grenada", code: "+1473", flag: "🇬🇩" },
  { iso2: "GP", country: "Guadeloupe", code: "+590", flag: "🇬🇵" },
  { iso2: "GU", country: "Guam", code: "+1671", flag: "🇬🇺" },
  { iso2: "GT", country: "Guatemala", code: "+502", flag: "🇬🇹" },
  { iso2: "GG", country: "Guernsey", code: "+44", flag: "🇬🇬" },
  { iso2: "GN", country: "Guinea", code: "+224", flag: "🇬🇳" },
  { iso2: "GW", country: "Guinea-Bissau", code: "+245", flag: "🇬🇼" },
  { iso2: "GY", country: "Guyana", code: "+592", flag: "🇬🇾" },
  { iso2: "HT", country: "Haiti", code: "+509", flag: "🇭🇹" },
  { iso2: "HN", country: "Honduras", code: "+504", flag: "🇭🇳" },
  { iso2: "HK", country: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { iso2: "HU", country: "Hungary", code: "+36", flag: "🇭🇺" },
  { iso2: "IS", country: "Iceland", code: "+354", flag: "🇮🇸" },
  { iso2: "IN", country: "India", code: "+91", flag: "🇮🇳" },
  { iso2: "ID", country: "Indonesia", code: "+62", flag: "🇮🇩" },
  { iso2: "IR", country: "Iran", code: "+98", flag: "🇮🇷" },
  { iso2: "IQ", country: "Iraq", code: "+964", flag: "🇮🇶" },
  { iso2: "IE", country: "Ireland", code: "+353", flag: "🇮🇪" },
  { iso2: "IM", country: "Isle of Man", code: "+44", flag: "🇮🇲" },
  { iso2: "IL", country: "Israel", code: "+972", flag: "🇮🇱" },
  { iso2: "IT", country: "Italy", code: "+39", flag: "🇮🇹" },
  { iso2: "CI", country: "Ivory Coast", code: "+225", flag: "🇨🇮" },
  { iso2: "JM", country: "Jamaica", code: "+1876", flag: "🇯🇲" },
  { iso2: "JP", country: "Japan", code: "+81", flag: "🇯🇵" },
  { iso2: "JE", country: "Jersey", code: "+44", flag: "🇯🇪" },
  { iso2: "JO", country: "Jordan", code: "+962", flag: "🇯🇴" },
  { iso2: "KZ", country: "Kazakhstan", code: "+7", flag: "🇰🇿" },
  { iso2: "KE", country: "Kenya", code: "+254", flag: "🇰🇪" },
  { iso2: "KI", country: "Kiribati", code: "+686", flag: "🇰🇮" },
  { iso2: "XK", country: "Kosovo", code: "+383", flag: "🇽🇰" },
  { iso2: "KW", country: "Kuwait", code: "+965", flag: "🇰🇼" },
  { iso2: "KG", country: "Kyrgyzstan", code: "+996", flag: "🇰🇬" },
  { iso2: "LA", country: "Laos", code: "+856", flag: "🇱🇦" },
  { iso2: "LV", country: "Latvia", code: "+371", flag: "🇱🇻" },
  { iso2: "LB", country: "Lebanon", code: "+961", flag: "🇱🇧" },
  { iso2: "LS", country: "Lesotho", code: "+266", flag: "🇱🇸" },
  { iso2: "LR", country: "Liberia", code: "+231", flag: "🇱🇷" },
  { iso2: "LY", country: "Libya", code: "+218", flag: "🇱🇾" },
  { iso2: "LI", country: "Liechtenstein", code: "+423", flag: "🇱🇮" },
  { iso2: "LT", country: "Lithuania", code: "+370", flag: "🇱🇹" },
  { iso2: "LU", country: "Luxembourg", code: "+352", flag: "🇱🇺" },
  { iso2: "MO", country: "Macau", code: "+853", flag: "🇲🇴" },
  { iso2: "MG", country: "Madagascar", code: "+261", flag: "🇲🇬" },
  { iso2: "MW", country: "Malawi", code: "+265", flag: "🇲🇼" },
  { iso2: "MY", country: "Malaysia", code: "+60", flag: "🇲🇾" },
  { iso2: "MV", country: "Maldives", code: "+960", flag: "🇲🇻" },
  { iso2: "ML", country: "Mali", code: "+223", flag: "🇲🇱" },
  { iso2: "MT", country: "Malta", code: "+356", flag: "🇲🇹" },
  { iso2: "MH", country: "Marshall Islands", code: "+692", flag: "🇲🇭" },
  { iso2: "MQ", country: "Martinique", code: "+596", flag: "🇲🇶" },
  { iso2: "MR", country: "Mauritania", code: "+222", flag: "🇲🇷" },
  { iso2: "MU", country: "Mauritius", code: "+230", flag: "🇲🇺" },
  { iso2: "YT", country: "Mayotte", code: "+262", flag: "🇾🇹" },
  { iso2: "MX", country: "Mexico", code: "+52", flag: "🇲🇽" },
  { iso2: "FM", country: "Micronesia", code: "+691", flag: "🇫🇲" },
  { iso2: "MD", country: "Moldova", code: "+373", flag: "🇲🇩" },
  { iso2: "MC", country: "Monaco", code: "+377", flag: "🇲🇨" },
  { iso2: "MN", country: "Mongolia", code: "+976", flag: "🇲🇳" },
  { iso2: "ME", country: "Montenegro", code: "+382", flag: "🇲🇪" },
  { iso2: "MS", country: "Montserrat", code: "+1664", flag: "🇲🇸" },
  { iso2: "MA", country: "Morocco", code: "+212", flag: "🇲🇦" },
  { iso2: "MZ", country: "Mozambique", code: "+258", flag: "🇲🇿" },
  { iso2: "MM", country: "Myanmar", code: "+95", flag: "🇲🇲" },
  { iso2: "NA", country: "Namibia", code: "+264", flag: "🇳🇦" },
  { iso2: "NR", country: "Nauru", code: "+674", flag: "🇳🇷" },
  { iso2: "NP", country: "Nepal", code: "+977", flag: "🇳🇵" },
  { iso2: "NL", country: "Netherlands", code: "+31", flag: "🇳🇱" },
  { iso2: "NC", country: "New Caledonia", code: "+687", flag: "🇳🇨" },
  { iso2: "NZ", country: "New Zealand", code: "+64", flag: "🇳🇿" },
  { iso2: "NI", country: "Nicaragua", code: "+505", flag: "🇳🇮" },
  { iso2: "NE", country: "Niger", code: "+227", flag: "🇳🇪" },
  { iso2: "NG", country: "Nigeria", code: "+234", flag: "🇳🇬" },
  { iso2: "NU", country: "Niue", code: "+683", flag: "🇳🇺" },
  { iso2: "KP", country: "North Korea", code: "+850", flag: "🇰🇵" },
  { iso2: "MK", country: "North Macedonia", code: "+389", flag: "🇲🇰" },
  { iso2: "MP", country: "Northern Mariana Islands", code: "+1670", flag: "🇲🇵" },
  { iso2: "NO", country: "Norway", code: "+47", flag: "🇳🇴" },
  { iso2: "OM", country: "Oman", code: "+968", flag: "🇴🇲" },
  { iso2: "PK", country: "Pakistan", code: "+92", flag: "🇵🇰" },
  { iso2: "PW", country: "Palau", code: "+680", flag: "🇵🇼" },
  { iso2: "PS", country: "Palestine", code: "+970", flag: "🇵🇸" },
  { iso2: "PA", country: "Panama", code: "+507", flag: "🇵🇦" },
  { iso2: "PG", country: "Papua New Guinea", code: "+675", flag: "🇵🇬" },
  { iso2: "PY", country: "Paraguay", code: "+595", flag: "🇵🇾" },
  { iso2: "PE", country: "Peru", code: "+51", flag: "🇵🇪" },
  { iso2: "PH", country: "Philippines", code: "+63", flag: "🇵🇭" },
  { iso2: "PL", country: "Poland", code: "+48", flag: "🇵🇱" },
  { iso2: "PT", country: "Portugal", code: "+351", flag: "🇵🇹" },
  { iso2: "PR", country: "Puerto Rico", code: "+1787", flag: "🇵🇷" },
  { iso2: "QA", country: "Qatar", code: "+974", flag: "🇶🇦" },
  { iso2: "CG", country: "Republic of the Congo", code: "+242", flag: "🇨🇬" },
  { iso2: "RE", country: "Réunion", code: "+262", flag: "🇷🇪" },
  { iso2: "RO", country: "Romania", code: "+40", flag: "🇷🇴" },
  { iso2: "RU", country: "Russia", code: "+7", flag: "🇷🇺" },
  { iso2: "RW", country: "Rwanda", code: "+250", flag: "🇷🇼" },
  { iso2: "BL", country: "Saint Barthélemy", code: "+590", flag: "🇧🇱" },
  { iso2: "SH", country: "Saint Helena", code: "+290", flag: "🇸🇭" },
  { iso2: "KN", country: "Saint Kitts and Nevis", code: "+1869", flag: "🇰🇳" },
  { iso2: "LC", country: "Saint Lucia", code: "+1758", flag: "🇱🇨" },
  { iso2: "MF", country: "Saint Martin", code: "+590", flag: "🇲🇫" },
  { iso2: "PM", country: "Saint Pierre and Miquelon", code: "+508", flag: "🇵🇲" },
  { iso2: "VC", country: "Saint Vincent and the Grenadines", code: "+1784", flag: "🇻🇨" },
  { iso2: "WS", country: "Samoa", code: "+685", flag: "🇼🇸" },
  { iso2: "SM", country: "San Marino", code: "+378", flag: "🇸🇲" },
  { iso2: "ST", country: "São Tomé and Príncipe", code: "+239", flag: "🇸🇹" },
  { iso2: "SA", country: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { iso2: "SN", country: "Senegal", code: "+221", flag: "🇸🇳" },
  { iso2: "RS", country: "Serbia", code: "+381", flag: "🇷🇸" },
  { iso2: "SC", country: "Seychelles", code: "+248", flag: "🇸🇨" },
  { iso2: "SL", country: "Sierra Leone", code: "+232", flag: "🇸🇱" },
  { iso2: "SG", country: "Singapore", code: "+65", flag: "🇸🇬" },
  { iso2: "SX", country: "Sint Maarten", code: "+1721", flag: "🇸🇽" },
  { iso2: "SK", country: "Slovakia", code: "+421", flag: "🇸🇰" },
  { iso2: "SI", country: "Slovenia", code: "+386", flag: "🇸🇮" },
  { iso2: "SB", country: "Solomon Islands", code: "+677", flag: "🇸🇧" },
  { iso2: "SO", country: "Somalia", code: "+252", flag: "🇸🇴" },
  { iso2: "ZA", country: "South Africa", code: "+27", flag: "🇿🇦" },
  { iso2: "KR", country: "South Korea", code: "+82", flag: "🇰🇷" },
  { iso2: "SS", country: "South Sudan", code: "+211", flag: "🇸🇸" },
  { iso2: "ES", country: "Spain", code: "+34", flag: "🇪🇸" },
  { iso2: "LK", country: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { iso2: "SD", country: "Sudan", code: "+249", flag: "🇸🇩" },
  { iso2: "SR", country: "Suriname", code: "+597", flag: "🇸🇷" },
  { iso2: "SE", country: "Sweden", code: "+46", flag: "🇸🇪" },
  { iso2: "CH", country: "Switzerland", code: "+41", flag: "🇨🇭" },
  { iso2: "SY", country: "Syria", code: "+963", flag: "🇸🇾" },
  { iso2: "TW", country: "Taiwan", code: "+886", flag: "🇹🇼" },
  { iso2: "TJ", country: "Tajikistan", code: "+992", flag: "🇹🇯" },
  { iso2: "TZ", country: "Tanzania", code: "+255", flag: "🇹🇿" },
  { iso2: "TH", country: "Thailand", code: "+66", flag: "🇹🇭" },
  { iso2: "TL", country: "Timor-Leste", code: "+670", flag: "🇹🇱" },
  { iso2: "TG", country: "Togo", code: "+228", flag: "🇹🇬" },
  { iso2: "TK", country: "Tokelau", code: "+690", flag: "🇹🇰" },
  { iso2: "TO", country: "Tonga", code: "+676", flag: "🇹🇴" },
  { iso2: "TT", country: "Trinidad and Tobago", code: "+1868", flag: "🇹🇹" },
  { iso2: "TN", country: "Tunisia", code: "+216", flag: "🇹🇳" },
  { iso2: "TR", country: "Turkey", code: "+90", flag: "🇹🇷" },
  { iso2: "TM", country: "Turkmenistan", code: "+993", flag: "🇹🇲" },
  { iso2: "TC", country: "Turks and Caicos Islands", code: "+1649", flag: "🇹🇨" },
  { iso2: "TV", country: "Tuvalu", code: "+688", flag: "🇹🇻" },
  { iso2: "UG", country: "Uganda", code: "+256", flag: "🇺🇬" },
  { iso2: "UA", country: "Ukraine", code: "+380", flag: "🇺🇦" },
  { iso2: "AE", country: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { iso2: "GB", country: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { iso2: "US", country: "United States", code: "+1", flag: "🇺🇸" },
  { iso2: "UY", country: "Uruguay", code: "+598", flag: "🇺🇾" },
  { iso2: "UZ", country: "Uzbekistan", code: "+998", flag: "🇺🇿" },
  { iso2: "VU", country: "Vanuatu", code: "+678", flag: "🇻🇺" },
  { iso2: "VA", country: "Vatican City", code: "+39", flag: "🇻🇦" },
  { iso2: "VE", country: "Venezuela", code: "+58", flag: "🇻🇪" },
  { iso2: "VN", country: "Vietnam", code: "+84", flag: "🇻🇳" },
  { iso2: "WF", country: "Wallis and Futuna", code: "+681", flag: "🇼🇫" },
  { iso2: "EH", country: "Western Sahara", code: "+212", flag: "🇪🇭" },
  { iso2: "YE", country: "Yemen", code: "+967", flag: "🇾🇪" },
  { iso2: "ZM", country: "Zambia", code: "+260", flag: "🇿🇲" },
  { iso2: "ZW", country: "Zimbabwe", code: "+263", flag: "🇿🇼" },
];

/** Find an entry by exact dial code (returns first match — useful for display). */
export function findByDialCode(code: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.code === code);
}

/**
 * Given an E.164 phone string, return the best-matching country code prefix
 * and the remaining local number. Tries longest prefixes first so e.g.
 * "+1684…" (American Samoa) doesn't collide with "+1" (US).
 */
export function extractCountryAndNumber(
  e164: string | null | undefined,
  fallback: string = "+971"
): { countryCode: string; localNumber: string } {
  if (!e164) return { countryCode: fallback, localNumber: "" };
  const sorted = [...COUNTRY_CODES].sort((a, b) => b.code.length - a.code.length);
  for (const cc of sorted) {
    if (e164.startsWith(cc.code)) {
      return { countryCode: cc.code, localNumber: e164.slice(cc.code.length) };
    }
  }
  return { countryCode: fallback, localNumber: e164.replace(/^\+/, "") };
}
